# Generated by Django 4.2.5 on 2024-02-09 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0004_category_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_onboarding",
            field=models.BooleanField(default=False),
        ),
    ]
