# Generated by Django 4.2.5 on 2023-10-31 10:05

import django.core.validators
from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_alter_profile_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(
                default="uploads/profile/img/avatar.png",
                upload_to=profiles.models.get_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["png", "jpg", "jpeg"]
                    )
                ],
            ),
        ),
    ]
