# Generated by Django 4.2.5 on 2024-02-09 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_alter_profile_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="team",
            field=models.CharField(
                choices=[
                    ("frontend", "Frontend"),
                    ("backend", "Backend"),
                    ("testing", "Testing"),
                    ("planning", "Planning"),
                    ("ideas", "Ideas"),
                    ("management", "Management"),
                ],
                max_length=200,
            ),
        ),
    ]
