# Generated by Django 4.2.5 on 2023-11-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0002_alter_category_options_blog"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="status",
            field=models.IntegerField(
                choices=[(0, "Darft"), (1, "Published")], default=0
            ),
        ),
    ]
