# Generated by Django 4.2.5 on 2024-02-09 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("areas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productionline",
            name="description",
            field=models.CharField(default="Not a description yet", max_length=500),
        ),
    ]
