# Generated by Django 4.2.5 on 2023-10-29 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("short_code", models.CharField(max_length=200)),
                ("updated", models.TimeField(auto_now=True)),
                ("created", models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
