# Generated by Django 4.2.5 on 2023-10-30 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_alter_profile_profile_picture"),
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="liked",
            field=models.ManyToManyField(
                blank=True, related_name="liked", to="profiles.profile"
            ),
        ),
    ]
