# Generated by Django 4.2.5 on 2023-10-31 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_like"),
    ]

    operations = [
        migrations.AlterField(
            model_name="like",
            name="value",
            field=models.CharField(
                choices=[("Like", "Like"), ("Unlike", "Unlike")],
                default="Like",
                max_length=10,
            ),
        ),
    ]
