# Generated by Django 4.2.5 on 2023-10-30 12:03

from django.db import migrations, models
import reports.models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0005_alter_report_options_problemreported_report"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problemreported",
            name="problem_id",
            field=models.CharField(
                blank=True,
                default=reports.models.random_code,
                max_length=12,
                unique=True,
            ),
        ),
    ]
