# Generated by Django 4.2.5 on 2024-01-28 20:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0007_alter_problemreported_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="report",
            name="end_hour",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="report",
            name="start_hour",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
