# Generated by Django 4.2.5 on 2024-01-28 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0009_remove_report_description_alter_report_end_hour_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="end_hour",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="report",
            name="start_hour",
            field=models.TimeField(),
        ),
    ]
