# Generated by Django 4.2.5 on 2024-01-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="is_completed",
        ),
        migrations.AddField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[("TD", "To Do"), ("IP", "In Progress"), ("DN", "Done")],
                default="TD",
                max_length=2,
            ),
        ),
    ]
