# Generated by Django 4.2.5 on 2024-01-26 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0004_task_assigned_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="deadline",
            field=models.DateField(blank=True, null=True),
        ),
    ]
