# Generated by Django 4.2.5 on 2024-01-26 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0005_task_deadline"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="urgency",
            field=models.CharField(
                choices=[("L", "Low"), ("M", "Medium"), ("H", "High")],
                default="L",
                max_length=1,
            ),
        ),
    ]
