# Generated by Django 4.2.5 on 2024-02-09 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("areas", "0001_initial"),
        ("todo", "0007_task_description_task_expected_time_task_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="areas.productionline",
            ),
        ),
    ]
