# Generated by Django 4.2.5 on 2024-02-09 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0008_alter_task_project"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="project",
        ),
    ]
